export default {
  normal: { name: "Normal", color: '#A8A878' },
  fighting: { name: "Lutador", color: '#C03028' },
  flying: { name: "Voador", color: '#A890F0' },
  poison: { name: "Veneno", color: '#A040A0' },
  ground: { name: "Terra", color: '#E0C068' },
  rock: { name: "Pedra", color: '#B8A038' },
  bug: { name: "Inseto", color: '#A8B81F' },
  ghost: { name: "Fantasma", color: '#705898' },
  steel: { name: "Metal", color: '#B8B8D0' },
  fire: { name: "Fogo", color: '#F08030' },
  water: { name: "Aquático", color: '#6890F0' },
  grass: { name: "Grama", color: '#78C850' },
  electric: { name: "Elétrico", color: '#F8D030' },
  psychic: { name: "Psíquico", color: '#F85888' },
  ice: { name: "Gelo", color: '#98D8D8' },
  dragon: { name: "Dragão", color: '#7038F8' },
  dark: { name: "Escuridão", color: '#705848' },
  fairy: { name: "Fada", color: '#EE99AC' },
  unknown: { name: "Desconhecido", color: '#68A090' },
  shadow: { name: "Sombra", color: '#592359' },
}